pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-creds')
        IMAGE_NAME = "stephen842/messaging-app"
        TAG = "latest"
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/stephen842/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                . venv/bin/activate
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                . venv/bin/activate
                pytest --junitxml=test-report.xml
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                cd messaging_app
                docker build -t ${IMAGE_NAME}:${TAG} .
                """
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh """
                echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                docker push ${IMAGE_NAME}:${TAG}
                """
            }
        }
    }

    post {
        always {
            junit 'messaging_app/test-report.xml'
        }
    }
}
