pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
    }

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/stephen842/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                cd messaging_app
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                cd messaging_app
                . venv/bin/activate
                pytest --junitxml=test-report.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'messaging_app/test-report.xml'
        }
    }
}

