apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
spec:
  type: ClusterIP
  selector:
    app: messaging_app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
